gencat/participa-catalunya

Gemfile.lock
README.md
config/docker/entrypoint.dev.sh
docker-compose.yml

Allow to user docker for development

---

decidim-courses/Gemfile
decidim-courses/Gemfile.lock

This fixes testing the gem with the correct decidim version

Courses: pin decidim version

---

decidim-resource_banks/Gemfile
decidim-resource_banks/Gemfile.lock

This fixes testing the gem with the correct decidim version

Resource banks: pin decidim version

---

decidim-courses/app/assets/stylesheets/decidim/courses/courses.scss
decidim-courses/app/views/decidim/courses/courses/show.html.erb
decidim-courses/config/locales/ca.yml
decidim-courses/config/locales/en.yml
decidim-courses/config/locales/es.yml
decidim-courses/spec/system/courses_spec.rb

Courses: show view sidebar style changes

---

decidim-courses/app/assets/stylesheets/decidim/courses/_cards.scss
decidim-courses/app/cells/decidim/courses/course_cell.rb
decidim-courses/app/cells/decidim/courses/course_m/data.erb
decidim-courses/app/cells/decidim/courses/course_m/date.erb
decidim-courses/app/cells/decidim/courses/course_m/footer.erb
decidim-courses/app/cells/decidim/courses/course_m/modality.erb
decidim-courses/app/cells/decidim/courses/course_m/multiple_dates.erb
decidim-courses/app/cells/decidim/courses/course_m/single_date.erb
decidim-courses/app/cells/decidim/courses/course_m_cell.rb
decidim-courses/app/cells/decidim/courses/course_s/multiple_dates.erb
decidim-courses/app/cells/decidim/courses/course_s/show.erb
decidim-courses/app/cells/decidim/courses/course_s_cell.rb
decidim-courses/config/locales/ca.yml
decidim-courses/config/locales/en.yml
decidim-courses/config/locales/es.yml
decidim-courses/spec/cells/decidim/courses/course_m_cell_spec.rb
decidim-courses/spec/cells/decidim/courses/course_s_cell_spec.rb

Home block content:
Courses index:

Courses: change cells styles

---

Gemfile
Gemfile.lock
config/secrets.yml
db/migrate/20210201083023_add_conferences.decidim_conferences.rb
db/migrate/20210201083024_add_conference_user_roles.decidim_conferences.rb
db/migrate/20210201083025_add_conference_speakers.decidim_conferences.rb
db/migrate/20210201083026_add_conference_invites.decidim_conferences.rb
db/migrate/20210201083027_add_conference_registrations.decidim_conferences.rb
db/migrate/20210201083028_add_conferences_partner.decidim_conferences.rb
db/migrate/20210201083029_add_relation_between_speaker_and_meeting.decidim_conferences.rb
db/migrate/20210201083030_add_conference_media_link.decidim_conferences.rb
db/migrate/20210201083031_add_conference_registration_types.decidim_conferences.rb
db/migrate/20210201083032_add_reference_registration_type_to_conference_registration.decidim_conferences.rb
db/migrate/20210201083033_add_registration_type_to_conference_invite.decidim_conferences.rb
db/migrate/20210201083034_add_diploma_fields_to_conference.decidim_conferences.rb
db/migrate/20210201083035_make_price_optional_conference_registration_type.decidim_conferences.rb
db/migrate/20210201083036_index_foreign_keys_in_decidim_conferences.decidim_conferences.rb
db/migrate/20210201083037_index_foreign_keys_in_decidim_conferences_conference_invites.decidim_conferences.rb
db/migrate/20210201083038_index_foreign_keys_in_decidim_conferences_conference_registrations.decidim_conferences.rb
db/schema.rb

Add conferences module and change smtp_authentication type

Add conferences module

---

app/assets/javascripts/datepicker-locales/foundation-datepicker.oc.js
config/initializers/decidim.rb
config/locales/oc.yml
config/locales/oc_accountability.yml
config/locales/oc_admin.yml
config/locales/oc_best-comment.yml
config/locales/oc_blog.yml
config/locales/oc_budgets.yml
config/locales/oc_comments.yml
config/locales/oc_conferences.yml
config/locales/oc_consultations.yml
config/locales/oc_core.yml
config/locales/oc_debates.yml
config/locales/oc_elections.yml
config/locales/oc_fix.yml
config/locales/oc_forms.yml
config/locales/oc_info.yml
config/locales/oc_initiatives.yml
config/locales/oc_login_register.yml
config/locales/oc_meetings.yml
config/locales/oc_pages.yml
config/locales/oc_participatory-processes.yml
config/locales/oc_proposals.yml
config/locales/oc_rails.yml
config/locales/oc_sortitions.yml
config/locales/oc_surveys.yml
config/locales/oc_system.yml
config/locales/oc_verifications.yml
config/locales/plurals.rb

Add occitan language as petitioned by the client.

Add occitan language

---

app/assets/stylesheets/overrides.scss

Apply font family Open Sans also on headers.

Add font-family open sans for headers

---

app/assets/javascripts/application.js
bin/delayed_job
config/application.rb
config/environments/production.rb
db/migrate/20210203092645_create_delayed_jobs.rb
db/schema.rb

Run delayed_job migrations, import jquery in application.js and add custom language fallbacks.

Run delayed_job migrations and add missing config

---

config/schedule.rb

Configure schedule.rb in order to run cron tasks.

Run Cron tasks

---

config/initializers/assets.rb

Remove images from assets.rb since it's not required and it results in errors.

Remove images from assets.rb

---

Gemfile.lock

Update department admin to include import/export assemblies fix

Fix department_admin import/export assemblies

---

decidim-courses/config/locales/ca.yml
decidim-courses/config/locales/es.yml
decidim-resource_banks/config/locales/ca.yml
decidim-resource_banks/config/locales/en.yml
decidim-resource_banks/config/locales/es.yml
decidim-resource_banks/lib/decidim/resource_banks/admin_engine.rb
decidim-resource_banks/spec/events/decidim/role_assigned_to_resource_bank_event_spec.rb
decidim-resource_banks/spec/shared/manage_resource_bank_admins_examples.rb
decidim-resource_banks/spec/shared/manage_resource_banks_examples.rb
decidim-resource_banks/spec/shared/resource_bank_administration_by_admin_shared_context.rb
decidim-resource_banks/spec/shared/resource_bank_administration_by_resource_bank_admin_shared_context.rb
decidim-resource_banks/spec/shared/resource_bank_administration_shared_context.rb
decidim-resource_banks/spec/system/admin/admin_manages_resource_bank_admins_spec.rb
decidim-resource_banks/spec/system/admin/admin_manages_resource_bank_attachment_collections_spec.rb
decidim-resource_banks/spec/system/admin/admin_manages_resource_bank_attachments_spec.rb
decidim-resource_banks/spec/system/admin/admin_manages_resource_banks_spec.rb
decidim-resource_banks/spec/system/admin/resource_bank_admin_accesses_admin_sections_spec.rb
decidim-resource_banks/spec/system/exploring_resource_banks_spec.rb
decidim-resource_banks/spec/system/resource_banks_spec.rb
spec/system/decidim/resource_banks/admin/department_admin_accesses_admin_sections_spec.rb

- Change button labels at Courses card
- Change title "Banc de recursos" for "Recursos"

Change some literals

---

.rubocop.yml
config/initializers/menus.rb
decidim-courses/lib/decidim/courses/admin_engine.rb
decidim-courses/lib/decidim/courses/engine.rb
decidim-resource_banks/lib/decidim/resource_banks/admin_engine.rb
decidim-resource_banks/lib/decidim/resource_banks/engine.rb
spec/features/overrides_and_customizations_spec.rb

This PR customizes the visible menus.

Custom sorting of public and admin menus

---

config/initializers/menus.rb
decidim-courses/app/cells/decidim/courses/registration_type/show.erb
decidim-courses/app/views/decidim/courses/registration_types/index.html.erb
decidim-courses/config/locales/ca.yml
decidim-courses/config/locales/en.yml
decidim-courses/config/locales/es.yml
decidim-courses/spec/system/course_registrations_spec.rb

**Fixes:**
- Registration_types index styling 
- Missing i18n for courses
- Conferences not showing in the public menu.

Fix registration_types styling, missing i18n for courses and public menu

---

decidim-courses/app/assets/stylesheets/decidim/courses/_cards.scss
decidim-courses/app/cells/decidim/courses/content_blocks/upcoming_courses/show.erb
decidim-courses/app/cells/decidim/courses/course_s/show.erb
decidim-courses/app/cells/decidim/courses/course_s_cell.rb
decidim-courses/config/locales/ca.yml
decidim-courses/config/locales/en.yml
decidim-courses/config/locales/es.yml
decidim-courses/spec/cells/decidim/courses/course_s_cell_spec.rb

Change home upcoming courses styling

---

Gemfile.lock

Get https://github.com/CodiTramuntana/decidim/pull/49

Upgrade decidim to fix validations for Conference.available_slots

---

decidim-courses/app/views/decidim/courses/courses/show.html.erb

This is a fix for the arguments that were setted in the contrary translation.

Arguments for total and available slots were setted inversely

---

app/assets/stylesheets/general/_footer.scss
app/assets/stylesheets/overrides.scss
decidim-courses/app/cells/decidim/courses/course_s/show.erb

Do some work to check that the custom styling is being correctly applied:
- Remove uppercases
- Change subtitles and color in alert. Change body font size.
- Changes in menu navbar and remove line in links. 
- Change styles in finder

Review Styles

---

decidim-courses/app/helpers/decidim/courses/courses_helper.rb
decidim-resource_banks/app/helpers/decidim/resource_banks/resource_banks_helper.rb

Do not show root scope in resources and courses filters.

Remove root scope in public helpers

---

app/decorators/decidim/courses/permissions/permissions_decorator.rb
app/decorators/decidim/resource_banks/permissions/permissions_decorator.rb

The permissions in the decorator didn't allow to show the administrator panel in the user menu

Change permissions for department_admin

---

Gemfile
Gemfile.lock
config/database.yml
config/environments/preprod.rb
config/secrets.yml
db/migrate/20210430092746_add_area_to_conferences.decidim_department_admin.rb
db/schema.rb

Get new `department_admin permissions` to administer conferences and participants.

Upgrade department_admin to get conferences and participants new extensions

---

Gemfile
Gemfile.lock

To get the fix in https://github.com/gencat/decidim-department-admin/pull/42

Update decidim-deptartment_admin to 0.2.1

---

config/locales/ca.yml
config/locales/en.yml
config/locales/es.yml
config/locales/oc.yml
db/migrate/20210920165500_update_literals.rb
db/schema.rb

Change some literals and translations

Translations and literals corrections

---

app/assets/stylesheets/overrides.scss

Changed css to center .speaker-bio on web view to avoid possible screen resolutions problems

Changed to center .speaker-bio on web view

---

config/locales/ca.yml
config/locales/en.yml
config/locales/es.yml
config/locales/oc.yml
config/locales/oc_admin.yml

add decidim.admin.models.user.fields.roles.conference_admin translations

Add decidim.admin.models.user.fields.roles.conference_admin translations

---

app/lib/decidim/extensions/locale_switcher_extension.rb
config/environment.rb
spec/controllers/concerns/locale_switcher_spec.rb

Set default locale
